# Basic
name:               "Pavel Vlasikhin"
description:        "Ruby on Rails developer"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "www.vlasikhin.ru"
author:             "me"
twitter:
  username:         "me"


# URL
baseurl:            ""
baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "notes"
    href:           "/"
  - name:           "CV"
    href:           "/eng"
  - name:           "Резюме"
    href:           "/rus"
  - name:           "contacts"
    href:           "/contacts"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag