title: Pavel Vlasikhin
description: Ruby on Rails developer
url: https://vlasikhin.github.io/
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
