# Site settings
title: "Pavel Vlasikhin's resume"
description: "Pavel Vlasikhin's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pavel Vlasikhin"
resume_title:                   "Ruby on Rails developer"
resume_contact_email:           "vlasikhinpavel@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/vlasikhin"
  resume_twitter_url:           "https://twitter.com/vlasikhin"
  # resume_dribbble_url:          "https://dribbble.com/username"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "www.linkedin.com/in/pavel-vlasikhin"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://vlasikhin.github.io/"

# Design settings
resume_theme:                   default

