# Basic
name:               "Pavel Vlasikhin"
description:        "Ruby on Rails developer"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://vlasikhin.github.io/"
author:             "vlasikhin"
twitter:
  username:         "vlasikhin"


# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "blog"
    href:           "https://vlasikhin.github.io/"
  - name:           "eng"
    href:           "/eng"
  - name:           "rus"
    href:           "/rus"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag